version: '3.8'

networks:
  project_allocation_tool_network:
    driver: bridge

services:
  nginx:
    image: nginx
    env_file:
      - ./nginx-reverse-proxy/.env
    ports:
      - "9090:9090"
    volumes:
      - ./nginx-reverse-proxy/nginx.template.conf:/etc/nginx/conf.d/default.template
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - user-service
      - project-allocation-service
    networks:
      - project_allocation_tool_network
    
  mysql-db:
    image: mysql:latest
    env_file:
      - ./mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/docker/volumes/mysql_data/_data:/var/lib/mysql
    networks:
      - project_allocation_tool_network

  rabbitmq:
    image: rabbitmq:latest
    env_file:
      - ./rabbitmq/.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - project_allocation_tool_network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    networks:
      - project_allocation_tool_network
    depends_on:
      - mysql-db

  project-allocation-service:
    build:
      context: ./project-allocation-service
      dockerfile: Dockerfile
    env_file:
      - ./project-allocation-service/.env
    networks:
      - project_allocation_tool_network
    depends_on:
      - mysql-db
      - rabbitmq
