pipeline {
    agent any

    tools {
       maven 'Maven'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    def mavenHome = tool 'Maven'
                    def mvnCmd = "${mavenHome}/bin/mvn"
                    sh "${mvnCmd} clean compile test package"
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts 'target/*.jar'
            }
        }
    }
}
